#!/bin/bash
set -e
set -o pipefail

# add group
if ! getent group | grep -q "^gltcore:" ; then
    echo "Creating system group: gltcore"
    groupadd --system gltcore
fi

# add user
if ! getent passwd | grep -q "^gltcore:"; then
    echo "Creating gltcore system user"
    useradd --gid "gltcore" --system -m gltcore
fi

# build nodejs addons
cd "/usr/opt/gltcore"
SKIP_BITCOIN_DOWNLOAD=1 npm rebuild

# setup data directory
mkdir -p "/home/gltcore/.gltcore/data"
chown -R gltcore:gltcore "/home/gltcore/.gltcore"

# start gltcore
if hash service 2> /dev/null; then
    service gltcore start || echo "gltcore could not be registered or started"
elif hash start 2> /dev/null; then
    start gltcore || echo "gltcore could not be registered or started"
elif hash systemctl 2> /dev/null; then
    {
        systemctl enable "gltcore.service" && \
            systemctl start "gltcore.service"
    } || echo "gltcore could not be registered or started"
else
    echo 'Your system does not appear to use upstart or systemd, so gltcore could not be started'
fi
