#!/bin/bash

set -e
set -o pipefail

if hash service 2> /dev/null; then
    service gltcore stop || echo "gltcore wasn't running!"
elif hash stop 2> /dev/null; then
    stop "$service_name" || echo "gltcore wasn't running!"
elif hash systemctl 2> /dev/null; then
    systemctl disable "gltcore.service" || echo "gltcore wasn't running!"
else
    echo "Your system does not appear to use upstart or systemd, so gltcore could not be stopped"
fi
